AWSTemplateFormatVersion: "2010-09-09"
Description: ALB template
Resources:
#ALB作成
  LoadBalancerResource:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Name: "cloudformationALB"
      Scheme: "internet-facing"
      Type: "application"
      Subnets: 
      - !ImportValue cloudformation-EC2publicSubnet1-id
      - !ImportValue cloudformation-EC2publicSubnet2-id
      SecurityGroups: 
      - !ImportValue cloudformationSGALB
      IpAddressType: "ipv4"
      Tags:
      - Key: "Name"
        Value: "CloudformationALB"
#ターゲットグループ作成
  TargetGroupResource:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Name: "TAG"
      VpcId: !ImportValue cloudformation-EC2VPC-id
      Protocol: "HTTP"
      ProtocolVersion: "HTTP1"
      Port: 80
      TargetType: "instance"
      Targets: 
      - Id: !ImportValue Cloudformation-EC2ID
        Port: 80
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: "/"
      HealthCheckPort: "traffic-port"
      HealthCheckProtocol: "HTTP"
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Matcher: 
        HttpCode: "200"
      Tags:
      - Key: "Name"
        Value: "TGN"
#リスナー設定
  ListenerResource:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      LoadBalancerArn: !Ref LoadBalancerResource
      Port: 80
      Protocol: "HTTP"
      DefaultActions: 
      - TargetGroupArn: !Ref TargetGroupResource
        Type: "forward"
#Outputsセクション設定  
Outputs:
  ALBOutput1:
    Value: !Ref LoadBalancerResource
    Export:
      Name: cloudformationALB

